# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 391, 471))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 110, 391, 471))
        self.label.setStyleSheet("border-image: url(:/imagenes/Diseno-sin-titulo-9-1024x1024.jpg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 351, 431))
        self.label_2.setStyleSheet("background-color: rgb(0,0,0,100);\n"
"border-radius:15px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 60, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 371, 451))
        self.label_4.setStyleSheet("border-image: url(:/i/Diseno-sin-titulo-9-1024x1024.jpg);\n"
"border-radius:20px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.campo_password = QtWidgets.QLineEdit(self.widget)
        self.campo_password.setGeometry(QtCore.QRect(30, 350, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.campo_password.setFont(font)
        self.campo_password.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(105,118,132,255);\n"
"color:rgb(255,255,255,230);\n"
"padding-bottom:7px;\n"
"")
        self.campo_password.setText("")
        self.campo_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.campo_password.setObjectName("campo_password")
        self.campo_usuario = QtWidgets.QLineEdit(self.widget)
        self.campo_usuario.setGeometry(QtCore.QRect(30, 310, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.campo_usuario.setFont(font)
        self.campo_usuario.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(105,118,132,255);\n"
"color:rgb(255,255,255,230);\n"
"padding-bottom:7px;\n"
"")
        self.campo_usuario.setText("")
        self.campo_usuario.setObjectName("campo_usuario")
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setGeometry(QtCore.QRect(140, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushBottom#pushBottom{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(20, 47, 78, 219), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"    color:rgb(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushBottom#pushBottom:hover{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"\n"
"QPushBottom#pushBottom:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(105,118,132,200);\n"
"}\n"
"\n"
"")
        self.login.setObjectName("login")
        self.label_4.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.campo_usuario.raise_()
        self.campo_password.raise_()
        self.login.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "LOG IN :"))
        self.campo_password.setPlaceholderText(_translate("MainWindow", "Password: "))
        self.campo_usuario.setPlaceholderText(_translate("MainWindow", "User Name: "))
        self.login.setText(_translate("MainWindow", "L O G  I N"))

# import res_r

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
